name: cacai
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  image: ^4.3.0
  logger: ^2.4.0
  http: ^1.2.2
  lottie: ^3.1.2
  shared_preferences: ^2.3.2
  tale_drawer: ^0.0.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.4
  flutter_zoom_drawer: ^3.2.0
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  dart_jsonwebtoken: ^2.14.1
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  sliding_up_panel: ^2.0.0+1
  flutter_onboarding: ^1.0.6
  font_awesome_flutter: ^10.8.0
  shimmer: ^3.0.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_speed_dial: ^7.0.0
  water_drop_nav_bar: ^2.2.2
  camera: ^0.11.0+2
  google_maps_flutter: ^2.10.1
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  share_plus: ^11.0.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.1
  stacked_generator: ^2.0.0-pre.1
  flutter_launcher_icons: ^0.14.3  # Flutter Launcher Icons package

flutter:
  uses-material-design: true
  assets:
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/upload.jpg
    - assets/animation.json
    - assets/signup_animation.json
    - assets/model.tflite
    - assets/images/
    - assets/images/ants.jpg
    - assets/images/aphis.jpg
    - assets/images/cacao_fruit_fly.jfif
    - assets/images/mirid.jpg
    - assets/images/weevil.jpg
    - assets/images/Mealybugs.jpg
    - assets/images/mono.jpg
    - assets/images/stem.jpg
    - assets/images/white.jpg
    - assets/images/chris.png
    - assets/images/how.jpeg
    - assets/images/ay.png
    - assets/hi.json
    - assets/animation/no_insect.json
    - assets/animation/loading.json
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/cacai.png"  # Path to your custom icon image
